# Health meter
print("Please enter the number of lives")
lives = int(input())
print("Please enter the energy level")
energy = int(input())
print("Please enter the shield level")
shield = int(input())
print()
print("Health has been set.")
print()
print("Lives:  ")
print("Energy: ")
print("Shield: ")